- type: entity
  abstract: true
  parent: ClothingUniformBase
  id: WHUniformBase
  components:
  - type: Clothing
    equipSound:
      path: /Audio/_RMC14/Handling/clothing_on.ogg #TODO replace sound
    unequipSound:
      path: /Audio/_RMC14/Handling/clothing_off.ogg
  - type: WebbingClothing
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
  - type: Sprite
    state: null
    layers:
    - state: icon
    - map: [ "enum.WebbingVisualLayers.Base" ]
  - type: Tag
    tags:
    - ClothMade
    - WhitelistChameleon
  - type: PlaytimeMedalHolder

- type: entity
  abstract: true
  parent: WHUniformBase
  id: WHFoldableUniformBase
  components:
  - type: Foldable
    canFoldInsideContainer: true
    unfoldVerbText: rmc-jacket-verb-unfold
    foldVerbText: rmc-jacket-verb-fold
  - type: FoldableClothing
    foldedEquippedPrefix: jacket

- type: entity
  abstract: true
  parent: WHUniformBase
  id: WHUniformSuitCoordsBase
  components:
  - type: SuitSensor
    controlsLocked: true
    randomMode: false
    mode: SensorCords

- type: entity
  abstract: true
  parent: [WHUniformBase, WHUniformSuitCoordsBase]
  id: WHFactionUniformBase
  components:
  - type: CMArmor
    armor: 10
